# Define variables interactively
variables:
- name: AppCenterApiToken
  value: 739256c4c5772f5c2840fa51d4f4912bf62be1c0
  prompt: true

- name: AppCenterAppName
  value: Android-App
  prompt: true

- name: DistributionGroupName
  value: Androidapp
  prompt: true

- name: AzureDevOpsUsername
  value: saurabhpathe
  prompt: true

stages:
- stage: Build
  jobs:
  - job: Build_Android
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseJavaVersion@0
      inputs:
        versionSpec: '11'
        installationPath: $(Java11_x64_InstallPath)
        installationName: 'Java11'
        jdkFile: 'adopt@1'
    - script: ./gradlew build
      displayName: 'Build Android APK'
    - publish: $(Build.SourcesDirectory)/app/build/outputs/apk/debug/app-debug.apk
      artifact: drop
      displayName: 'Publish APK Artifact'

- stage: DeployToAppCenter
  jobs:
  - job: Deploy_Android
    displayName: 'Deploy to App Center'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - script: |
        curl -X POST -H "Content-Type: application/json" -d '{
          "token": "$(AppCenterApiToken)",
          "file_path": "$(System.ArtifactsDirectory)/app-debug.apk",
          "app_name": "$(AppCenterAppName)",
          "group": "$(DistributionGroupName)",
          "release_notes": "Automated build from Azure DevOps"
        }' https://api.appcenter.ms/v0.1/apps/$(AzureDevOpsUsername)/$(AppCenterAppName)/uploads/releases
      displayName: 'Upload APK to App Center'
