# Define variables without values
variables:
- name: 739256c4c5772f5c2840fa51d4f4912bf62be1c0
- name: Android-App
- name: Androidapp
- name: saurabhpathe

stages:
- stage: Build
  jobs:
  - job: Build_Android
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseJavaVersion@0
      inputs:
        versionSpec: '11'
        installationPath: $(Java11_x64_InstallPath)
        installationName: 'Java11'
        jdkFile: 'adopt@1'
    - script: ./gradlew build
      displayName: 'Build Android APK'
    - publish: $(Build.SourcesDirectory)/app/build/outputs/apk/debug/app-debug.apk
      artifact: drop
      displayName: 'Publish APK Artifact'

- stage: DeployToAppCenter
  jobs:
  - job: Deploy_Android
    displayName: 'Deploy to App Center'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - powershell: |
        $AppCenterApiToken = Read-Host -Prompt "Enter your App Center API token"
        $AppCenterAppName = Read-Host -Prompt "Enter your App Center app name"
        $DistributionGroupName = Read-Host -Prompt "Enter your distribution group name"
        $AzureDevOpsUsername = Read-Host -Prompt "Enter your Azure DevOps username"

        # Use the entered values in the API call
        $ApiUrl = "https://api.appcenter.ms/v0.1/apps/$AzureDevOpsUsername/$AppCenterAppName/uploads/releases"
        $JsonBody = @{
          "token" = $AppCenterApiToken
          "file_path" = "$(System.ArtifactsDirectory)/app-debug.apk"
          "app_name" = $AppCenterAppName
          "group" = $DistributionGroupName
          "release_notes" = "Automated build from Azure DevOps"
        } | ConvertTo-Json

        Invoke-RestMethod -Uri $ApiUrl -Method Post -Headers @{"Content-Type"="application/json"} -Body $JsonBody
      displayName: 'Upload APK to App Center'
