# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

jobs:
- job: Build_Android
  displayName: 'Build Android APK'
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'assembleDebug'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactStagingDirectory)'
    inputs:
      SourceFolder: ''
      Contents: '**/*.apk'
      TargetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'

- job: Deploy_Android
  displayName: 'Deploy to App Center'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)'
  - powershell: |
    .\upload-to-appcenter.ps1
  displayName: 'Upload APK to App Center'



